config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

# Prefix Verb   URI Pattern               Controller#Action
#     flats GET    /flats(.:format)          flats#index
#           POST   /flats(.:format)          flats#create
#  new_flat GET    /flats/new(.:format)      flats#new
# edit_flat GET    /flats/:id/edit(.:format) flats#edit
#      flat GET    /flats/:id(.:format)      flats#show
#           PATCH  /flats/:id(.:format)      flats#update
#           PUT    /flats/:id(.:format)      flats#update
#           DELETE /flats/:id(.:format)      flats#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [:show, :edit, :update, :destroy]
  def index
    @flats = Flat.all
  end

  def show; end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit; end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def find_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="container mt-5">
    <%= simple_form_for(@flat) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guests %>
      <%= f.button :submit, class: 'btn btn-success' %>
    <% end %>
</div>

app/views/flats/edit.html.erb
<%= render 'form' %>

app/views/flats/index.html.erb
<div class="container mt-5">
    <h3>Make yourself at <strong>home</strong>!</h3>
    <p>make the world your primary home.</p>
    <%= link_to 'create new', new_flat_path, class: 'btn btn-success'%>
  </div>


<div class="container">
  <div class="row">
  <% @flats.each do | flat | %>
    <div class="col-6">
      <div class="card-trip mt-3">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
        <div class="card-trip-infos">
          <div>
            <h2><%= link_to flat.name, flat_path(flat) %></h2>
            <p><%= flat.address %></p>
            <p><%= flat.description %></p>
            <p>Guests <%= flat.number_of_guests %></p>
          </div>
          <h2 class="card-trip-pricing"><%= flat.price_per_night %></h2>
          <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= render 'form' %>

app/views/flats/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1459535653751-d571815e906b?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1920&q=80);">
  <div class="container">
    <h1>Made possible by <strong>Hosts</strong>!</h1>
    <p>make the world your primary home.</p>
    <a class="btn btn-flat" href="#">book now</a>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card-trip mt-3">
        <img src="https://images.unsplash.com/photo-1556912167-f556f1f39fdf?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=3160&q=80" />
        <div class="card-trip-infos">
          <div>
            <h2><%= @flat.name %></h2>
            <p><%= @flat.address %></p>
            <p><%= @flat.description %></p>
            <p>Guests <%= @flat.number_of_guests %></p>
          </div>
          <h2 class="card-trip-pricing"><%= @flat.price_per_night %></h2>
          <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
        </div>
        <div class="d-flex justify-content-around">
          <%= link_to "see all", flats_path, class: 'text-success' %>
          <%= link_to "edit", edit_flat_path(@flat), class: 'text-primary' %>
          <%= link_to "delete", flat_path(@flat), method: :delete, data: { confirm: 'Please confirm'}, class: 'text-danger' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <%= yield %>

  </body>
</html>